name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      
      - name: Autenticando no Docker Registry
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
    
      - name: Docker build kube-news
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src 
          file: ./src/Dockerfile
          push: true
          tags: |
            luangddev/imersao-kubenews:v${{ github.run_number }}
            luangddev/imersao-kubenews:latest
  
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3.5.3
      
      - name: Autenticar o AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name:  Configurar do kubectl
        shell: bash
        run: |
          aws eks update-kubeconfig --name eks-desafioimersao --region us-east-1
          
      - name: Deploy de kube-news
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            k8s/deploy-kubenews.yaml
          images:
            luangddev/imersao-kubenews:v${{ github.run_number }}
            
        
      
  
